### PR TITLE
Sample/transit roadbook

### PR DESCRIPTION
**Pull request by shwetadeshmukh**
## Describe your changes
- Added new code sample for Transit Service with roadbook

## Checklist:

- [x] My code follows the style guidelines for this repo
- [x] I have performed a self-review of my code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings/errors
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I don't require ops changes for this PR to go to prod
- [x] This change does not include a migration

### CODE REVIEW

**Comment by gaelsimon** [comment]
Nice one.
Only one little things. when no route are returned, remove the Transit Route Roadbook and maybe add a message using the `displayOrHideError` method.
Thanks

**Review by gaelsimon — CHANGES_REQUESTED** [review]
Nice one.
Only one little things. when no route are returned, remove the Transit Route Roadbook and maybe add a message using the `displayOrHideError` method.
Thanks

**Comment by shwetadeshmukh** [comment]
> Nice one. Only one little things. when no route are returned, remove the Transit Route Roadbook and maybe add a message using the `displayOrHideError` method. Thanks

Done ✔️

**Review by gaelsimon — APPROVED** [review]

**Comment by gaelsimon** [comment]
Ok,
Just a little reminder, as this repo implements SemanticVersioning (`fix: commit message`, `feat: commit message`...) if it's not used, no release will be triggered and therefore no deploy to devdoc.
I just add a quick commit to trigger this.

**Comment by shwetadeshmukh** [comment]
> Ok, Just a little reminder, as this repo implements SemanticVersioning (`fix: commit message`, `feat: commit message`...) if it's not used, no release will be triggered and therefore no deploy to devdoc. I just add a quick commit to trigger this.

Oh ok. Thanks for letting me know. I will keep that in mind.

**Pull request merged**
